[package]
name = "strapi"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
serde_yaml_ng = "0.10.0"
tokio = { version = "1", features = ["full"] }
